[package]
name = "rust-playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zcash_primitives = "0.11.0"
zcash_client_backend = "0.9.0"
orchard = "0.4.0"
